package asteroids

// Constants
WINDOW_WIDTH :: 1600
WINDOW_HEIGHT :: 1000

PLAYER_SPEED :: 300
MAX_SPEED :: 300
PLAYER_ROT_SPEED :: 1
FRICTION :: 0.99

PROJECTILE_SPEED :: 350
PROJECTILE_LIFETIME :: 1.8
PROJECTILE_SIZE :: 5
PROJECTILE_SPAWN_RATE :: 0.2

MAX_ASTEROIDS :: 20
MAX_ASTEROID_SPEED :: 200
MAX_ASTEROID_SIZE :: 40
MIN_ASTEROID_SIZE :: 15
MAX_ASTEROID_ROT_SPEED :: 1
ASTEROID_SPAWN_RATE :: 2
MAX_ASTEROID_SIDES :: 9

// Types
Vec2f32 :: [2]f32